language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - env: TARGET=x86_64-unknown-linux-gnu
      # TODO revert to nightly when rustc bug is fixed
      rust: nightly-2019-07-10

before_install: set -e

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
