[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["concurrency", "embedded", "no-std"]
description = "The Real Time for The Masses (RTFM) meta language"
documentation = "https://docs.rs/rtfm-syntax"
edition = "2018"
keywords = []
license = "MIT OR Apache-2.0"
name = "rtfm-syntax"
repository = "https://github.com/japaric/rtfm-syntax"
version = "0.4.0-alpha.1"

[dependencies]
indexmap = "1.0.2"
proc-macro2 = "0.4.30"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "0.15.34"

[dev-dependencies]
mock = { path = "mock" }
compiletest_rs = "0.3.22"
quote = "0.6.12"

[features]
device = []

[workspace]
members = [
  "mock",
]
