[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["concurrency", "embedded", "no-std"]
description = "The Real Time for The Masses (RTFM) meta language"
documentation = "https://docs.rs/rtfm-syntax"
edition = "2018"
keywords = []
license = "MIT OR Apache-2.0"
name = "rtfm-syntax"
repository = "https://github.com/japaric/rtfm-syntax"
version = "0.4.0-alpha.1"

[[test]]
name = "ui"
required-features = ["compiletest_rs"]

[dependencies]
indexmap = "1.0.2"
proc-macro2 = "1"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "1"

[dev-dependencies]
mock = { path = "mock" }
quote = "1"

[dependencies.compiletest_rs]
optional = true
version = "0.3.22"

[workspace]
members = [
  "mock",
]
